import {createSync} from './sync.js?v=21f3358aa63b';
import {id,today,addDays,days,monthDate,day,money,emptyState,validateState,calculate,budgets,budgetPeriod,payroll,shiftPay,cancelTransaction,cancelGeneratedEvent,resolvePayment,debtRemaining,settleDebt,debtInterest,debtAvailable,recordDebtActivity} from './core.js?v=21f3358aa63b';
const testing=new URLSearchParams(location.search).has('test');
const KEY='kurashi-budget-v1'+(testing?'-test':''),BACKUP=KEY+'-previous';
let state=emptyState(),loadError='',tab='home',section='',filter='all',group='all',view='list',selectedDate='',calendarMonth=today().slice(0,7)+'-01',result,setupStep=0;
try{const saved=localStorage.getItem(KEY);if(saved)state=validateState(JSON.parse(saved));}catch(e){loadError='保存データを読み込めませんでした。元のデータは上書きせず保護しています。バックアップから復元してください。';}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yen=n=>money(n),dateLabel=s=>s?`${Number(s.slice(5,7))}月${Number(s.slice(8,10))}日`:'未設定';
const names=(collection,key)=>state[collection].find(x=>x.id===key)?.name||'未設定';
const accountOptions=()=>state.accounts.map(a=>[a.id,a.name+(a.active===false?'（アーカイブ）':'')]);
const categoryOptions=(selected='')=>[['','未分類'],...state.categories.filter(a=>a.active!==false||a.id===selected).map(a=>[a.id,a.name+(a.active===false?'（削除済み）':'')])];
const paymentOptions=()=>[...accountOptions().map(([v,l])=>['a:'+v,l]),...state.cards.map(c=>['c:'+c.id,c.name+'（クレジット）']),...state.debitCards.map(c=>['d:'+c.id,c.name+'（デビット）'])];
const btn=(text,action,extra='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const icon=name=>({home:'⌂',record:'＋',schedule:'▦',manage:'☷'})[name];
function toast(text){if($('#dialog').open){let error=$('#dialog .dialog-error');if(!error){error=document.createElement('p');error.className='alert danger dialog-error';error.setAttribute('role','alert');$('#dialog .dialog-head').after(error);}error.textContent=text;}$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function commit(fn){if(loadError){toast(loadError);return false;}const before=structuredClone(state);try{fn();validateState(state);const next=JSON.stringify(state);localStorage.setItem(BACKUP,JSON.stringify(before));localStorage.setItem(KEY,next);render();sync.schedule();return true;}catch(e){state=before;toast('保存できませんでした：'+e.message);return false;}}
function openDialog(title,content){const d=$('#dialog');d.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2>${btn('✕','close','aria-label="閉じる"','icon-button')}</div>${content}`;if(!d.open)d.showModal();}
function closeDialog(){$('#dialog').close();}
function row(title,sub,amount,action='',extra='',negative=false){return `<div class="row"><div class="row-icon ${negative?'out':'in'}">${negative?'↗':'↙'}</div><div class="row-main"><strong>${esc(title)}</strong><small>${esc(sub)}</small></div><div class="row-end"><strong class="${negative?'':'income'}">${amount}</strong>${action?btn('詳細',action,extra,'text-button'):''}</div></div>`;}
function empty(text,action='',label='追加する',extra=''){return `<div class="empty"><span>○</span><p>${text}</p>${action?btn(label,action,extra,'secondary'):''}</div>`;}
function heading(eyebrow,title,action=''){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1></div>${action}</div>`;}
function render(){
 result=calculate(state);document.title=`${yen(result.safe)} · くらしの余白`;
 $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#home"><img src="./icon.svg" alt="" width="34" height="34"><span>くらしの余白<small>MY MONEY, MY PACE</small></span></a><nav aria-label="メイン">${[['home','ホーム'],['record','記録'],['schedule','予定'],['manage','管理']].map(([k,l])=>btn(`<span aria-hidden="true">${icon(k)}</span>${l}`,'tab',`data-tab="${k}" aria-current="${tab===k?'page':'false'}"`,tab===k?'active':'')).join('')}</nav><div class="sidebar-bottom"><span class="local-dot"></span> ${esc(sync.getStatus().message)}<br><small>${sync.getStatus().signedIn?'Googleアカウントで同期':'端末内保存'}</small></div></aside><div class="workspace"><header class="topbar"><span>毎日の安心を、少しずつ。</span><span>${new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></header><main>${loadError?`<div class="alert danger">${esc(loadError)}${btn('復元','restore')}</div>`:''}${sync.getStatus().conflict?`<div class="alert danger">同期する変更の確認が必要です。${btn('変更を確認','sync-conflict')}</div>`:sync.getStatus().error?`<div class="alert info">${esc(sync.getStatus().message)}${btn(sync.getStatus().signedIn?'再同期':'ログインを再試行',sync.getStatus().signedIn?'sync-retry':'sync-login')}</div>`:''}${({home:home,record:record,schedule:schedule,manage:manage})[tab]()}</main><footer>登録した情報に基づく見込みです。未登録の支出・収入は含みません。</footer></div>${btn('＋','quick','aria-label="すばやく追加"','fab')}<nav class="bottom-nav" aria-label="メインタブ">${[['home','ホーム'],['record','記録'],['schedule','予定'],['manage','管理']].map(([k,l])=>btn(`<span aria-hidden="true">${icon(k)}</span>${l}`,'tab',`data-tab="${k}" aria-current="${tab===k?'page':'false'}"`,tab===k?'active':'')).join('')}</nav>`;
}
function home(){
 const b=budgets(state).filter(c=>c.active!==false&&c.budget>0),upcoming=result.events.filter(e=>e.date>=today()).slice(0,5),recent=[...state.transactions,...result.allEvents.filter(e=>e.status==='actual'&&!e.transactionId&&!e.id.startsWith('opening-card:')).map(e=>({...e,automatic:true}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);
 return heading('OVERVIEW','お金に、余白を。',btn('内訳を見る ↗','breakdown','','secondary'))+(!state.setupDone?setupCard():'')+`<section class="hero" aria-label="使っていいお金"><div><div class="hero-label"><span class="status-dot"></span> 今、使っていいお金</div><button class="hero-amount" data-action="breakdown">${yen(result.safe)}<span>↗</span></button><p>${dateLabel(result.shortEnd)}までの90日間を確認${result.end>result.shortEnd?' ＋ 登録済みの長期支出':''}</p></div><div class="hero-art" aria-hidden="true"><div></div><div></div><div></div><span>余白</span></div><div class="hero-bottom"><span>計算対象の資産 <strong>${yen(result.assets)}</strong></span><span>最低維持資金 <strong>${yen(state.settings.minimum)}</strong></span></div></section><div class="metric-grid"><section class="card metric"><span class="metric-icon">☀</span><div><p>今日の使用目安</p><strong>${yen(result.daily)}<small> / 日</small></strong><small>${dateLabel(result.reference)}まで、あと${result.dayCount}日</small></div></section><section class="card metric"><span class="metric-icon green">↗</span><div><p>貯金に回せる金額</p><strong>${yen(result.savable)}</strong><small>${esc(names('accounts',result.savingsSource))}から移す場合</small></div>${btn('確認','savings','','text-button')}</section></div>${alerts()}<div class="home-grid"><section class="card"><div class="section-title"><h2>予算の残り</h2>${btn('管理 →','section','data-section="categories"','text-button')}</div><small>${dateLabel(budgetPeriod(state).start)}〜${dateLabel(budgetPeriod(state).end)}</small>${b.length?b.map(c=>`<div class="budget"><div><span>${esc(c.name)}</span><strong class="${c.remaining<0?'red':''}">${yen(c.remaining)}</strong></div><div class="track"><i style="width:${Math.min(100,Math.max(0,c.used/c.budget*100))}%" class="${c.remaining<0?'over':''}"></i></div><small>${yen(c.used)} / ${yen(c.budget)}</small></div>`).join(''):empty('カテゴリごとの予算を設定できます。','section','予算を設定','data-section="categories"')}</section><section class="card"><div class="section-title"><h2>直近の予定</h2>${btn('すべて →','tab','data-tab="schedule"','text-button')}</div>${upcoming.length?upcoming.map(eventRow).join(''):empty('これからの予定はまだありません。','quick','予定を追加')}</section></div><section class="card recent"><div class="section-title"><h2>最近の記録</h2>${btn('すべて →','tab','data-tab="record"','text-button')}</div>${recent.length?recent.map(t=>t.automatic?eventRow(t):transactionRow(t)).join(''):empty('最初の記録をつけてみましょう。','tab','記録する','data-tab="record"')}</section>`;
}
function setupCard(){const steps=[['accounts','資産口座と現在残高'],['settings','最低維持資金'],['employers','収入・勤務先'],['recurring','固定費'],['cards','クレジットカード'],['goals','長期支出']];return `<section class="setup"><div><strong>まずは、お金の置き場所から</strong><p>口座残高と最低維持資金だけで開始できます。</p></div><div class="setup-steps">${steps.map(([key,label],i)=>btn(`<span>${i+1}</span>${label}`,'section',`data-section="${key}"`,state[key]?.length?'done':'')).join('')}</div>${state.accounts.length?btn('この内容で使い始める','finish-setup','','secondary'):''}<small>より正確に計算するには、給与予定・固定費・カードを追加してください。</small></section>`;}
function alerts(){return `${result.minimum<0?`<div class="alert danger"><strong>登録済みの収支では ${yen(-result.minimum)} 不足する見込みです</strong><p>${dateLabel(result.limitingDate)}に、最低維持資金・安全バッファを下回ります。</p></div>`:''}${result.shortfalls.map(w=>`<div class="alert"><strong>${dateLabel(w.date)} · ${esc(names('accounts',w.accountId))}が ${yen(w.amount)} 不足する見込み</strong><p>${esc(w.name)}に備えて、口座間の振替を確認してください。</p>${btn('振替を記録','new-tx','data-kind="transfer"','text-button')}</div>`).join('')}${result.overdue.length?`<div class="alert"><strong>期日を過ぎた未確認の予定が${result.overdue.length}件あります</strong><p>未払い・未入金として本日の計算に含めています。</p>${btn('予定を確認','tab','data-tab="schedule"','text-button')}</div>`:''}${result.warnings.map(w=>`<div class="alert danger">${esc(w)}</div>`).join('')}`;}
function eventRow(e){const amount=e.cardPurchase?-e.amount:e.amount;return row(e.name,`${dateLabel(e.date)} · ${names('accounts',e.accountId)}${e.status==='actual'?' · 確定':''}`,yen(amount),'event',`data-id="${esc(e.id)}"`,amount<0);}
function transactionRow(t){const payment=t.debitCardId?names('debitCards',t.debitCardId)+'（デビット）':t.cardId?names('cards',t.cardId):names('accounts',t.accountId);return row(t.name||({expense:'支出',income:'収入',transfer:'振替',adjustment:'残高調整',cancel:'取消',refund:'返金',fee:'手数料'})[t.kind],`${dateLabel(t.date)} · ${payment} · ${t.status==='actual'?'確定':'予定'}`,yen(t.amount),'tx-detail',`data-id="${esc(t.id)}"`,['expense','fee','transfer'].includes(t.kind));}
function record(){const auto=result.allEvents.filter(e=>e.status==='actual'&&!e.transactionId&&!e.id.startsWith('opening-card:'));const history=[...state.transactions.map(t=>({date:t.date,html:transactionRow(t)})),...auto.map(e=>({date:e.date,html:eventRow(e)}))].sort((a,b)=>b.date.localeCompare(a.date));return heading('RECORD','日々のお金を記録',btn('記録を追加','new-tx','','primary'))+`<section class="card"><div class="segmented">${[['expense','支出'],['income','収入'],['transfer','振替']].map(([k,l])=>btn(l,'new-tx',`data-kind="${k}"`)).join('')}</div><div class="section-title"><h2>取引履歴</h2><span class="badge">${history.length}件</span></div>${history.length?history.map(x=>x.html).join(''):empty('支出・収入・振替をここから記録できます。','new-tx','最初の記録を追加')}</section>`;}
function schedule(){let es=result.events.filter(e=>(filter==='all'||(filter==='expense'?e.amount<0:e.amount>0))&&(group==='all'||e.source===group));const sums=n=>result.events.filter(e=>e.date>=today()&&e.date<=addDays(today(),n)&&e.amount<0&&!e.toAccountId).reduce((a,e)=>a-e.amount,0);return heading('PLAN','これからの予定',btn('予定を追加','new-tx','data-planned="true"','primary'))+`<div class="metric-grid compact"><section class="card"><small>今後30日の支出</small><strong>${yen(sums(30))}</strong></section><section class="card"><small>今後90日の支出</small><strong>${yen(sums(90))}</strong></section></div><section class="card"><div class="schedule-toolbar"><div class="segmented">${[['list','一覧'],['calendar','カレンダー']].map(([k,l])=>btn(l,'view',`data-view="${k}"`,view===k?'selected':'')).join('')}</div><select aria-label="予定の種類" id="schedule-group">${[['all','すべての支払い'],['fixed','固定費'],['subscription','サブスク'],['card','クレジットカード'],['debt','借入・分割'],['longterm','長期予定'],['salary','給与'],['manual','その他']].map(([v,l])=>`<option value="${v}" ${group===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="chips">${[['all','すべて'],['expense','支出'],['income','収入']].map(([k,l])=>btn(l,'filter',`data-filter="${k}"`,filter===k?'selected':'')).join('')}</div>${view==='calendar'?calendar(es):es.length?es.map(eventRow).join(''):empty('この条件の予定はありません。')}</section>`;}
function calendar(es){const first=calendarMonth,offset=day(first).getUTCDay(),end=addDays(monthDate(first,1,1),-1);const cells=Array.from({length:offset},()=>'<div></div>');for(let i=1;i<=Number(end.slice(8));i++){const date=first.slice(0,8)+String(i).padStart(2,'0'),list=es.filter(e=>e.date===date),income=list.filter(e=>e.amount>0).reduce((n,e)=>n+e.amount,0),out=list.filter(e=>e.amount<0).reduce((n,e)=>n-e.amount,0);cells.push(btn(`<span>${i}</span>${income?`<small class="income">+${income.toLocaleString()}</small>`:''}${out?`<small>−${out.toLocaleString()}</small>`:''}`,'day',`data-date="${date}"`,`${date===today()?'today':''} ${date===selectedDate?'selected':''}`));}return `<div class="section-title">${btn('‹','month','data-delta="-1" aria-label="前の月"','icon-button')}<h2>${Number(first.slice(0,4))}年 ${Number(first.slice(5,7))}月</h2>${btn('›','month','data-delta="1" aria-label="次の月"','icon-button')}</div><div class="calendar">${['日','月','火','水','木','金','土'].map(d=>`<small>${d}</small>`).join('')}${cells.join('')}</div><div class="day-events">${selectedDate?`<h3>${dateLabel(selectedDate)}の予定</h3>${es.filter(e=>e.date===selectedDate).map(eventRow).join('')||'<p class="muted">予定はありません。</p>'}`:'<p class="muted">日付を選ぶと、その日の予定を確認できます。</p>'}</div>`;}
const groupNames={accounts:'資産口座',cards:'クレジットカード',debitCards:'デビットカード',recurring:'固定費・サブスク',goals:'長期支出予定',debts:'借入・分割払い',employers:'勤務先・給与設定',shifts:'シフト',templates:'シフトテンプレート',advances:'給与先払い',categories:'予算カテゴリ',settings:'家計ルール・計算設定'};
function manage(){if(section==='settings')return settingsView();if(section)return collectionView(section);return heading('MANAGE','家計のしくみを整える')+syncCard()+`<div class="manage-grid">${[['01','お金の置き場所',['accounts']],['02','支払い・契約',['cards','debitCards','recurring','debts','goals']],['03','収入・仕事',['employers','shifts','templates','advances']],['04','家計ルール',['categories','settings']]].map(([n,title,keys])=>`<section class="card"><span class="eyebrow">${n}</span><h2>${title}</h2>${keys.map(k=>btn(`${groupNames[k]}<span>${Array.isArray(state[k])?state[k].filter(x=>x.active!==false).length:''}　›</span>`,'section',`data-section="${k}"`,'menu-row')).join('')}</section>`).join('')}</div><section class="card backup"><div><h2>データのバックアップ</h2><p>同期の有無にかかわらず、定期的に書き出してください。</p></div><div class="actions">${btn('バックアップ出力','export','','secondary')}${btn('ファイルから復元','restore','','secondary')}</div></section>`;}
function collectionView(key){const list=key==='categories'?state[key].filter(x=>x.active!==false):state[key];return heading('MANAGE',groupNames[key],btn('＋ 追加','entity-new',`data-collection="${key}"`,'primary'))+btn('‹ 管理に戻る','back-manage','','text-button')+(key==='shifts'?`<div class="actions">${btn('テンプレートで複数日登録','batch-shifts','','secondary')}</div>`:'')+`<section class="card">${list.length?list.map(x=>{let desc=x.memo||'',amount='';if(key==='accounts'){desc=`${({bank:'銀行',cash:'現金',emoney:'電子マネー',ic:'交通IC',savings:'貯金専用',other:'その他'})[x.type]||''} · 計算対象${x.include?'ON':'OFF'}`;amount=yen(result.current[x.id]);}if(key==='categories'){const b=budgets(state).find(b=>b.id===x.id);desc=`使用済み ${yen(b.used)} / 残り ${yen(b.remaining)}`;amount=yen(x.budget||0);}if(key==='shifts'){const e=state.employers.find(e=>e.id===x.employerId);desc=`${dateLabel(x.date)} ${x.start}〜${x.end} · ${names('employers',x.employerId)}`;amount=e?yen(shiftPay(x,e).net):'';}if(key==='debitCards'){desc=`${names('accounts',x.accountId)} · 利用時に銀行残高から引落`; }if(key==='cards'){desc=`${x.closeDay}日締め · ${x.payDay}日支払 · ${names('accounts',x.accountId)}`;amount=yen(cardOutstanding(x));}if(key==='debts'){desc=`${x.kind==='revolving'?'残高型':'分割払い型'} · 残高 ${yen(debtRemaining(state,x.id))}${x.kind==='revolving'?` · 利用可能 ${yen(debtAvailable(x))}`:` · 年率${x.apr}%`}`;amount=x.settlementId||debtRemaining(state,x.id)<=0?'完済':yen(x.payment)+'/月';}if(key==='goals'){desc=`期限 ${dateLabel(x.dueDate)}`;amount=yen(x.amount);}if(key==='recurring'){desc=`${({monthly:'毎月',yearly:'毎年',weekly:'毎週',daily:'毎日'})[x.cycle]} · ${x.variable?'変動額':'固定額'}`;amount=yen(x.amount);}if(key==='employers'){desc=`${x.closeDay}日締め · ${x.payDay}日給与`;amount=yen(x.hourly)+'/時';}if(key==='advances'){desc=`${dateLabel(x.date)} · ${names('employers',x.employerId)}`;amount=yen(x.amount);}return `<div class="entity-row ${x.active===false?'archived':''}"><div><strong>${esc(x.name||desc)}${x.active===false?'<span class="badge">アーカイブ</span>':''}</strong><small>${esc(desc)}</small></div><strong>${amount}</strong>${btn('詳細','entity-detail',`data-collection="${key}" data-id="${esc(x.id)}"`,'secondary')}</div>`;}).join(''):empty('まだ登録されていません。','entity-new','追加する',`data-collection="${key}"`)}</section>${key==='categories'?deletedCategories():''}${key==='employers'?salarySummary():''}`;}
function deletedCategories(){const list=state.categories.filter(x=>x.active===false);return list.length?`<details class="card"><summary>削除済みのカテゴリ（${list.length}件）</summary>${list.map(x=>`<div class="entity-row"><strong>${esc(x.name)}</strong>${btn('詳細・元に戻す','entity-detail',`data-collection="categories" data-id="${esc(x.id)}"`,'secondary')}</div>`).join('')}</details>`:'';}
function cardOutstanding(c){return Math.max(0,result.allEvents.filter(e=>e.cardId===c.id&&e.cardPurchase&&e.date<=today()).reduce((n,e)=>n+e.amount,0)-result.allEvents.filter(e=>e.cardId===c.id&&!e.cardPurchase&&e.status==='actual'&&e.date<=today()).reduce((n,e)=>n+(e.reserveRelease||0),0));}
function salarySummary(){return `<section class="card"><h2>シフトからの給与見込み</h2>${payroll(state).map(g=>row(g.name,`${dateLabel(g.date)} · 信用度反映後 ${yen(g.trusted)} · 先払い可能 ${yen(g.advanceAvailable)}`,yen(g.amount),'event',`data-id="${esc(g.id)}"`)).join('')||'<p class="muted">シフトを登録すると給与が計算されます。</p>'}</section>`;}
function field(name,label,type='text',value='',options=[],help='',required=true){if(name==='categoryId')required=false;const base=`name="${name}" id="f-${name}" ${required?'required':''}`;let input=type==='select'?`<select ${base}>${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:type==='checkbox'?`<input type="checkbox" ${base.replace('required','')} ${value?'checked':''}>`:type==='textarea'?`<textarea ${base}>${esc(value)}</textarea>`:`<input type="${type}" ${base} value="${esc(value)}" ${type==='number'?'step="any" inputmode="decimal"':''}>`;return `<label class="field ${type==='checkbox'?'check':''}" for="f-${name}"><span>${label}</span>${input}${help?`<small>${help}</small>`:''}</label>`;}
const schema={
 accounts:[['name','口座名'],['type','種類','select','bank',[['bank','銀行'],['cash','現金'],['emoney','電子マネー'],['ic','交通IC'],['savings','貯金専用'],['other','その他']]],['balance','開始残高','number',0],['balanceDate','開始日','date',today(),'','この日の記録を含める前の残高です。既存口座のズレは「残高調整」を使ってください。'],['include','使っていいお金の計算に含める','checkbox',true]],
 debitCards:[['name','カード名'],['accountId','紐づける銀行口座','bankAccounts']],
 cards:[['name','カード名'],['closeDay','締め日（末日は31）','number',31],['payDay','支払日（末日は31）','number',10],['payOffset','締め月から何か月後に支払うか','number',1],['accountId','引落口座','accounts'],['limit','利用可能枠','number',0],['openingOutstanding','登録時点の未払額','number',0,'','個別に入力済みのカード利用は含めないでください。'],['openingDueDate','登録時点の未払額の引落日','date',addDays(today(),30)]],
 recurring:[['name','名称'],['amount','予定金額','number',0],['kind','入出金','select','expense',[['expense','支出'],['income','収入']]],['group','種類','select','fixed',[['fixed','固定費'],['subscription','サブスクリプション']]],['cycle','周期','select','monthly',[['monthly','毎月'],['yearly','毎年'],['weekly','毎週'],['daily','毎日']]],['startDate','最初の予定日','date',today()],['endDate','終了日（任意）','date','','','',false],['payDay','月・年払いの日（末日は31）','number',Number(today().slice(8))],['payment','支払方法 / 入金先','payments'],['categoryId','カテゴリ','categories'],['variable','変動額として扱う','checkbox',false],['confidence','予定収入の信用度（%）','number',100]],
 goals:[['name','名称'],['amount','必要額','number',0],['dueDate','支払期限','date',addDays(today(),120)],['accountId','支払元','accounts'],['memo','メモ','textarea','','','',false]],
 debts:[['kind','種類','select','installment',[['installment','分割払い型'],['revolving','残高型借入']]],['name','名称'],['totalPayable','総支払額（手数料込み）','number',0],['feeTotal','手数料（総支払額に含む）','number',0],['principal','当初元金','number',0],['balance','現在の未払い残高','number',0],['apr','年利（%）','number',0],['payment','毎月返済額（元利合計）','number',0],['payDay','支払日','number',27],['startDate','次回支払月・日','date',today()],['months','残り返済回数（0＝完済まで）','number',0],['accountId','支払元','accounts']],
 employers:[['name','勤務先名'],['hourly','基本時給','number',1100],...['日','月','火','水','木','金','土'].map((d,i)=>['weekday'+i,d+'曜の時給加算','number',0]),['holidayAdd','祝日の時給加算','number',0],['nightRate','深夜加算率（22〜翌5時 / %）','number',25],['overtimeHours','1日の残業開始時間','number',8],['overtimeRate','残業加算率（%）','number',25],['transport','1勤務あたり交通費','number',0],['allowance','給与1回あたり固定手当','number',0],['breakMinutes','標準休憩（分）','number',60],['closeDay','給与締め日','number',31],['payDay','給料日','number',15],['payOffset','締め月から何か月後の給与か','number',1],['accountId','入金先','accounts'],['deduct','控除予測を含める','checkbox',false],['deductionRate','控除予測率（%）','number',0],['rounding','丸め方法','select','ceil',[['ceil','1円未満切り上げ'],['floor','切り捨て'],['round','四捨五入']]],['advancePercent','勤務済み給与の先払い割合（%）','number',0],['advanceCap','先払い上限（0＝上限なし）','number',0],['advanceFee','先払い手数料','number',0],['transferFee','先払い振込手数料','number',0]],
 shifts:[['employerId','勤務先','employers'],['date','勤務日','date',today()],['start','出勤','time','09:00'],['end','退勤（同時刻以前なら翌日）','time','18:00'],['breakMinutes','休憩（分）','number',60],['status','勤務状態','select','confirmed',[['worked','勤務済み'],['confirmed','確定シフト'],['tentative','未確定予定']]],['holiday','祝日加算を適用する','checkbox',false]],
 templates:[['name','テンプレート名'],['employerId','勤務先','employers'],['start','出勤','time','09:00'],['end','退勤','time','18:00'],['breakMinutes','休憩（分）','number',60]],
 advances:[['employerId','勤務先','employers'],['date','受取日','date',today()],['payDate','差し引く給料日','date',addDays(today(),30)],['amount','先払い対象額（手数料込）','number',0],['fee','手数料合計','number',0],['accountId','入金先','accounts'],['status','状態','select','actual',[['actual','受取済み'],['planned','予定']]]],
 categories:[['name','カテゴリ名'],['budget','給与期間ごとの予算','number',0]]
};
function debtSchema(x){return x.kind==='revolving'?[schema.debts[0],['name','借入先名'],['limit','利用限度額','number',100000],['balance','現在借入残高','number',0],['apr','年利（%）','number',0],['startDate','次回返済日','date',today()],['payment','次回返済額（元利合計）','number',2000],['accountId','引落口座','accounts'],['allowDraw','追加借入を許可','checkbox',true],['interestDate','利息計算の基準日','date',today(),[],'通常は前回の利息清算日です。現在残高の登録日を基準にする場合、その日までの未払利息を下欄に入力してください。'],['accruedInterest','基準日までの未払利息','number',0]]:schema.debts;}
function schemaFields(key,x={}){return (key==='debts'?debtSchema(x):schema[key]).map(([name,label,type='text',def='',options=[],help='',required=true])=>{let value=x[name]??def;if(['accounts','bankAccounts','categories','employers','payments'].includes(type)){options=type==='bankAccounts'?state.accounts.filter(a=>['bank','savings'].includes(a.type)).map(a=>[a.id,a.name]):type==='accounts'?accountOptions():type==='categories'?categoryOptions(x[name]):type==='employers'?state.employers.map(e=>[e.id,e.name]):paymentOptions();if(type==='payments')value=x.debitCardId?'d:'+x.debitCardId:x.cardId?'c:'+x.cardId:x.accountId?'a:'+x.accountId:value;type='select';}return field(name,label,type,value,options,help,required);}).join('');}
function entityForm(key,keyId=''){const x=state[key].find(x=>x.id===keyId)||{};if(key==='debts'){debtForm(keyId,x);return;}if(key==='advances'&&keyId&&x.status==='actual'){toast('受取済みの先払いは、記録から取消を作成してから正しい内容を追加してください。');return;}if(['shifts','templates','advances'].includes(key)&&!state.employers.length){toast('先に勤務先を登録してください。');section='employers';tab='manage';render();return;}if(['accounts','categories','templates'].includes(key)===false&&!state.accounts.length){toast('先に資産口座を登録してください。');section='accounts';tab='manage';render();return;}openDialog(`${groupNames[key]}を${keyId?'編集':'追加'}`,`<form data-form="entity" data-collection="${key}" data-id="${esc(keyId)}"><div class="form-grid">${schemaFields(key,x)}</div>${key==='employers'||key==='shifts'?'<p class="form-note">給与は設定した加算率による概算です。休憩は各時間帯に比例配分します。週単位の残業・税額表・祝日自動判定は使わず、実際の給与を予定の詳細から確定できます。</p>':''}<div class="form-actions"><button class="primary">保存して再計算</button>${btn('戻る','close','','secondary')}</div></form>`);}
function entityDetail(key,keyId){const x=state[key].find(x=>x.id===keyId);if(key==='debts'){debtDetail(keyId);return;}openDialog(x.name||groupNames[key],`<dl class="detail-list">${schema[key].filter(([n])=>n!=='payment').map(([n,l,t])=>`<div><dt>${esc(l)}</dt><dd>${esc(['accounts','bankAccounts'].includes(t)?names('accounts',x[n]):t==='employers'?names('employers',x[n]):t==='checkbox'?x[n]?'ON':'OFF':x[n]??'—')}</dd></div>`).join('')}</dl>${key==='cards'?`<p>現在利用額 ${yen(cardOutstanding(x))} / 利用可能枠 ${yen(x.limit)}</p><h3>カード利用明細</h3>${result.allEvents.filter(e=>e.cardId===keyId&&e.cardPurchase&&!e.id.startsWith('opening-card:')).sort((a,b)=>b.date.localeCompare(a.date)).map(eventRow).join('')||'<p class="muted">利用明細はまだありません。</p>'}`:''}<div class="actions">${btn('編集','entity-edit',`data-collection="${key}" data-id="${esc(keyId)}"`,'primary')}${key==='accounts'?btn('残高を照合','reconcile',`data-id="${esc(keyId)}"`,'secondary'):''}${key==='debts'&&x.active!==false&&debtRemaining(state,keyId)>0?btn('残額をまとめて返済','debt-settle',`data-id="${esc(keyId)}"`,'primary'):''}${key==='categories'?btn('上へ移動','category-up',`data-id="${esc(keyId)}"`,'secondary'):''}${btn(key==='categories'?(x.active===false?'元に戻す':'削除'):x.active===false?'有効に戻す':'アーカイブ','archive',`data-collection="${key}" data-id="${esc(keyId)}"`,'secondary')}</div><p class="form-note">${key==='categories'?'削除すると予算一覧と新しい記録の選択肢から外れます。過去の記録と予定のカテゴリは保持され、削除済みの一覧から元に戻せます。':'アーカイブしても過去の取引・参照は残ります。口座は計算対象から外れ、定期ルール・長期予定・借入・シフトは予定生成を停止します。既に登録されたカード利用と勤務実績は維持します。'}</p>`);}
function transactionForm(kind='expense',planned=false,copy=null,editId=''){if(!state.accounts.length){toast('記録する前に資産口座を登録してください。');entityForm('accounts');return;}const t=copy||{},actualEdit=editId?state.transactions.find(t=>t.id===editId):null;if(actualEdit?.status==='actual'){toast('確定済みの記録は取消・返金で修正してください。');return;}openDialog(editId?'予定を編集':'お金を記録',`<form data-form="transaction" data-id="${esc(editId)}"><div class="form-grid">${field('kind','種類','select',t.kind||kind,[['expense','支出'],['income','収入'],['transfer','振替'],['fee','手数料'],['refund','返金']])}${field('amount','金額','number',t.amount||'')}${field('date','日付','date',t.date||today())}${field('categoryId','カテゴリ','select',t.categoryId||'',categoryOptions(t.categoryId))}${field('payment','支払元 / 入金先','select',t.debitCardId?'d:'+t.debitCardId:t.cardId?'c:'+t.cardId:t.accountId?'a:'+t.accountId:'',paymentOptions())}${field('toAccountId','振替先（振替のみ）','select',t.toAccountId||'',[['','選択してください'],...accountOptions()], '',false)}${field('fee','振替手数料','number',t.fee||0)}${field('name','店名・相手先','text',t.name||'','','',false)}${field('memo','メモ','textarea',t.memo||'','','',false)}${field('status','予定 / 実績','select',t.status||(planned?'planned':'actual'),[['actual','確定（残高に反映）'],['planned','予定']])}${field('confidence','予定収入の信用度（%）','number',t.confidence??state.settings.confidence.extra)}${field('repeat','この内容を毎月繰り返す','checkbox',false)}</div><p class="form-note">デビットカードは利用時に紐づく銀行残高から引かれます。クレジットカードは使える額を確保し、引落日に残高へ反映します。</p><div class="form-actions"><button class="primary">保存して再計算</button></div></form>`);}
function debtForm(keyId='',draft={}){const saved=state.debts.find(d=>d.id===keyId);const x={kind:'installment',...saved,...draft};openDialog(`借入・分割払いを${keyId?'編集':'追加'}`,`<form data-form="entity" data-collection="debts" data-id="${esc(keyId)}"><div class="form-grid">${schemaFields('debts',x)}</div><p class="form-note">${x.kind==='revolving'?'利用可能額は資産に含めません。登録する残高は現在の実残高です。基準日から年利・365日で日割りの利息を概算し、返済時には貸し手の実額を優先します。追加借入・返済は詳細画面から記録してください。':'総支払額には手数料を含めてください。固定の分割手数料の場合は年利0%、現在の残高に未払いの総額を登録してください。既存の年利付き借入は従来の月利計算を維持します。'}</p><div class="form-actions"><button class="primary">保存して再計算</button>${btn('戻る','close','','secondary')}</div></form>`);}
function debtDetail(keyId){const d=state.debts.find(d=>d.id===keyId),revolving=d.kind==='revolving',balance=debtRemaining(state,keyId),history=state.transactions.filter(t=>t.debtId===keyId||t.debtSettlement?.debtId===keyId).sort((a,b)=>b.date.localeCompare(a.date));openDialog(d.name,`<p class="eyebrow">${revolving?'残高型借入':'分割払い型'}</p><p class="detail-amount">${yen(balance)}</p><dl class="detail-list">${(revolving?[['利用限度額',yen(d.limit)],['利用可能額',yen(debtAvailable(d))],['追加借入',d.allowDraw?'可能':'不可'],['年利',d.apr+'%'],['次回返済日',d.startDate],['次回返済額',yen(d.payment)],['引落口座',names('accounts',d.accountId)],['本日までの利息概算',yen(debtInterest(d))]]:[['総支払額（手数料込み）',yen(d.totalPayable||d.principal||0)],['手数料（内数）',yen(d.feeTotal||0)],['毎月の支払額',yen(d.payment)],['残り支払回数',d.months||'完済まで'],['次回支払日',d.startDate],['年利',d.apr+'%'],['支払元',names('accounts',d.accountId)]]).map(([l,v])=>`<div><dt>${esc(l)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="actions">${btn('編集','entity-edit',`data-collection="debts" data-id="${esc(keyId)}"`,'secondary')}${revolving&&d.active!==false&&d.allowDraw&&debtAvailable(d)>0?btn('追加借入を記録','debt-draw',`data-id="${esc(keyId)}"`,'primary'):''}${revolving&&d.active!==false&&balance>0?btn('返済を記録','debt-repay',`data-id="${esc(keyId)}"`,'primary'):''}${d.active!==false&&balance>0?btn('残額をまとめて返済','debt-settle',`data-id="${esc(keyId)}"`,'secondary'):''}${btn(d.active===false?'有効に戻す':'アーカイブ','archive',`data-collection="debts" data-id="${esc(keyId)}"`,'secondary')}</div>${revolving?'<p class="form-note">利用可能額は借入の枠であり、資産・使っていいお金には含めません。返済額は元金と利息・手数料に分けて記録します。取消は新しい借入・返済から順に行ってください。</p>':''}<h3>借入・返済・利息の履歴</h3>${history.map(transactionRow).join('')||'<p class="muted">記録はまだありません。</p>'}`);}
function debtActivityForm(keyId,kind,full=false){const d=state.debts.find(d=>d.id===keyId),interest=debtInterest(d),amount=kind==='draw'?'':full?d.balance+interest:Math.min(d.payment,d.balance+interest),next=d.startDate>today()?d.startDate:monthDate(today(),1,d.payDay);openDialog(kind==='draw'?'追加借入を記録':full?'残額をまとめて返済':'返済を記録',`<p>${esc(d.name)} · 残高 ${yen(d.balance)} · 利用可能 ${yen(debtAvailable(d))}</p><form data-form="debt-activity" data-id="${esc(keyId)}"><input type="hidden" name="kind" value="${kind}">${full?'<input type="hidden" name="full" value="true">':''}<div class="form-grid">${field('amount',kind==='draw'?'追加借入額（手数料控除前）':'実際の支払総額','number',amount)}${kind==='repayment'?field('interest','利息（実額）','number',Math.min(Number(amount),interest),[],'初期値は概算です。貸し手の実際の利息に修正してください。'):''}${field('fee','手数料','number',0)}${field('date','取引日','date',today())}${field('accountId',kind==='draw'?'入金先口座':'引落口座','select',d.accountId,state.accounts.filter(a=>a.active!==false).map(a=>[a.id,a.name]))}${kind==='repayment'?(full?`<input type="hidden" name="nextDate" value="${next}">`:field('nextDate','次回返済日','date',next)):''}${field('categoryId','利息・手数料のカテゴリ','select','',categoryOptions())}${field('memo','メモ','textarea','','','',false)}</div><p class="form-note">${kind==='draw'?'借入残高を増やし、入金先に借入額を加算します。手数料があれば別の支出として差し引きます。':'支払総額から利息・手数料を引いた元金分だけ借入残高を減らします。口座からは総額を1回だけ引きます。利息の実額を優先し、取引日までの未払利息を清算済みとして扱います。'}既に同じ入出金を記録済みの場合は先に取り消してください。</p><div class="form-actions"><button class="primary">${kind==='draw'?'借入と入金を記録':'返済と残高を更新'}</button>${btn('戻る','close','','secondary')}</div></form>`);}
function debtSettlementForm(keyId){const d=state.debts.find(d=>d.id===keyId),remaining=debtRemaining(state,keyId);openDialog('残額をまとめて返済',`<p><strong>${esc(d.name)}</strong>の残り元金：<strong>${yen(remaining)}</strong></p><form data-form="debt-settlement" data-id="${esc(keyId)}"><div class="form-grid">${field('amount','実際の支払総額（元金・利息・手数料込み）','number',remaining,[],'貸し手に確認した実際の金額を入力してください。利息・手数料の自動見積もりは行いません。')}${field('date','返済日','date',today())}${field('accountId','支払元口座','select',d.accountId,state.accounts.filter(a=>a.active!==false).map(a=>[a.id,a.name]))}${field('categoryId','カテゴリ','select','',categoryOptions())}${field('memo','メモ','textarea','','','',false)}</div><p class="form-note">支出を1件記録し、借入残高を0円にして未確定の返済予定を終了します。過去の確定済み返済は残ります。同じ支払いを記録済みなら先にその記録を取り消してください。誤入力は記録の詳細から「取消を記録」で戻せます。</p><div class="form-actions"><button class="primary">一括返済を記録して完済にする</button>${btn('戻る','close','','secondary')}</div></form>`);}
function txDetail(keyId){const t=state.transactions.find(t=>t.id===keyId);openDialog(t.name||'取引の詳細',`<p class="detail-amount">${yen(t.amount)}</p><dl class="detail-list">${[['日付',t.date],['状態',t.status==='actual'?'確定':'予定'],['支払方法',t.debitCardId?names('debitCards',t.debitCardId)+'（デビット）':t.cardId?names('cards',t.cardId):names('accounts',t.accountId)],...(t.debtOperation?[['借入先',names('debts',t.debtId)],['取引',t.debtOperation.kind==='draw'?'追加借入':'返済'],['操作の総額',yen(t.debtOperation.total)],['利息',yen(t.debtOperation.interest)],['手数料',yen(t.debtOperation.fee)]]:[]),...(t.debtSettlement?[['返済元金',yen(t.debtSettlement.principal)],['利息・手数料',yen(t.debtSettlement.extra)]]:[]),['カテゴリ',names('categories',t.categoryId)],['メモ',t.memo||'—']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="actions">${t.debtSettlement||t.debtOperationId?'':btn('複製','duplicate-tx',`data-id="${esc(keyId)}"`,'secondary')}${t.status==='planned'?btn('編集 / 実績にする','edit-tx',`data-id="${esc(keyId)}"`,'primary'):''}${(t.debtId||t.debtSettlement)&&t.reverses?'<span class="badge">取消の記録</span>':!state.transactions.some(x=>x.reverses===keyId)?btn(t.status==='planned'?'予定を削除':'取消を記録','cancel-tx',`data-id="${esc(keyId)}"`,'secondary'):'<span class="badge">取消済み</span>'}</div>`);}
function eventDetail(keyId){const e=result.allEvents.find(e=>e.id===keyId);if(!e){toast('対象の予定が見つかりません。');return;}if(e.transactionId){txDetail(e.transactionId);return;}if(e.status!=='actual'&&e.debtId&&state.debts.find(d=>d.id===e.debtId)?.kind==='revolving'){debtActivityForm(e.debtId,'repayment');return;}if(e.status==='actual'){openDialog(e.name,`<p class="detail-amount">${yen(e.amount)}</p><p>${e.date} · ${esc(names('accounts',e.accountId))} · 確定</p><p class="form-note">確定済みの履歴は保存されています。修正する場合は取消を記録し、正しい金額を新しく記録してください。</p>${!state.transactions.some(t=>t.reversesEvent===e.id)?btn('取消を記録','reverse-event',`data-id="${esc(e.id)}"`,'secondary'):'<span class="badge">取消済み</span>'}`);return;}openDialog(e.name,`<form data-form="event" data-id="${esc(keyId)}"><p class="form-note">手動入力を優先します。この予定1件だけを置き換えるので、二重登録されません。</p><div class="form-grid">${field('amount',e.cardPurchase?'利用金額（返金はマイナス）':'金額（支出はマイナス）','number',e.amount)}${field('date','日付','date',e.date)}${field('accountId','支払元 / 入金先','select',e.accountId,accountOptions())}${e.cardPurchase?field('dueDate','引落予定日','date',e.dueDate):''}${field('status','状態','select',e.status,[['planned','予定'],['actual',e.cardPurchase?'利用確定（残高は引落時に反映）':'入出金済み（実際の残高に反映）']])}${field('confidence','予定収入の信用度（%）','number',e.confidence??100)}</div>${e.interest!==undefined?`<p>利息 ${yen(e.interest)} · 返済後元金 ${yen(e.remaining)}</p>`:''}<div class="form-actions"><button class="primary">確定して再計算</button>${btn('この予定を取り消す','skip-event',`data-id="${esc(keyId)}"`,'secondary')}</div></form>`);}
function settingsView(){const s=state.settings;return heading('RULES','家計ルール・計算設定')+btn('‹ 管理に戻る','back-manage','','text-button')+`<section class="card"><form data-form="settings"><div class="form-grid">${field('minimum','最低維持資金','number',s.minimum)}${field('buffer','安全バッファ','number',s.buffer)}${field('dailySpecial','日割りから除く特別支出枠','number',s.dailySpecial,[],'予定支出として登録済みの金額は重ねて入力しないでください。')}${field('referenceDate','1日の使用目安の基準日','date',s.referenceDate)}${field('salaryDay','予算期間の開始日（給料日）','number',s.salaryDay)}${field('savingsSource','貯金に移す元の口座','select',s.savingsSource,accountOptions())}${[['worked','勤務済み給与'],['confirmed','確定シフト'],['tentative','未確定シフト'],['extra','臨時収入予定']].map(([k,l])=>field(k,`${l}の信用度（%）`,'number',s.confidence[k])).join('')}</div><p class="form-note">90日先までと、登録した長期支出・既知のカード請求の期限まで確認します。同日の支出は収入より先に処理し、入金前の不足も確認します。使わなかった分は残高に残り、翌日の目安に反映されます。</p><button class="primary">設定を保存</button></form></section>`;}
function breakdown(){const points=result.points,at=points.find(p=>p.date===result.limitingDate&&p.available===result.minimum)||points[0];openDialog('使っていいお金の計算根拠',`<p class="detail-amount">${yen(result.safe)}</p><p>${dateLabel(result.end)}までの残高推移のうち、最も余裕が少ない時点から計算しています。</p><dl class="detail-list">${[['現在の計算対象資産',result.assets],['現在のカード未払確保',-result.reservedNow],['期間内の信用度反映後の入金',result.income],['期間内の出金（振替元を含む）',-result.expense],['最低維持資金',-state.settings.minimum],['安全バッファ',-state.settings.buffer],['90日以降の予定による追加確保',-result.longReserve]].map(([k,v])=>`<div><dt>${k}</dt><dd>${yen(v)}</dd></div>`).join('')}</dl><div class="alert info"><strong>制約になる日：${dateLabel(result.limitingDate)}</strong><p>その時点の対象口座残高 ${yen(at.balance)} − 未払カード確保 ${yen(at.reserved)} − 最低維持資金・バッファ ${yen(result.floor)} = ${yen(result.minimum)}</p><small>上の期間合計の単純な足し引きではありません。長期確保は残高推移に含まれており、二重に引きません。</small></div><details><summary>日付ごとの残高を確認</summary><div class="table-scroll"><table><thead><tr><th>日付</th><th>対象残高</th><th>未払確保</th><th>余裕</th></tr></thead><tbody>${points.map(p=>`<tr><td>${p.date}</td><td>${yen(p.balance)}</td><td>${yen(p.reserved)}</td><td class="${p.available<0?'red':''}">${yen(p.available)}</td></tr>`).join('')}</tbody></table></div></details>`);}
function batchShifts(){if(!state.templates.length){toast('先にシフトテンプレートを登録してください。');entityForm('templates');return;}const month=today().slice(0,7)+'-01';openDialog('シフトをまとめて登録',`<form data-form="batch"><div class="form-grid">${field('templateId','テンプレート','select','',state.templates.filter(x=>x.active!==false).map(x=>[x.id,x.name]))}${field('month','勤務月','month',month.slice(0,7))}${field('status','勤務状態','select','confirmed',[['worked','勤務済み'],['confirmed','確定'],['tentative','未確定']])}</div><div id="batch-days" class="batch-days">${batchDays(month)}</div><p class="form-note">日付を複数選択してください。同じ勤務先・日付・時間帯のシフトは重複登録しません。</p><button class="primary">選択した日を登録</button></form>`);}
function batchDays(month){return Array.from({length:Number(addDays(monthDate(month,1,1),-1).slice(8))},(_,i)=>`<label><input type="checkbox" name="dates" value="${month.slice(0,8)+String(i+1).padStart(2,'0')}"><span>${i+1}</span></label>`).join('');}
function exportData(){const json=JSON.stringify(state,null,2),blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),filename=`kurashi-backup-${today()}.json`;openDialog('バックアップ出力',`<p>保存したファイルは「ファイルから復元」で読み込めます。</p><p class="actions"><a class="primary" id="backup-download" href="${url}" download="${filename}">JSONファイルを保存</a></p><details><summary>ファイルを保存できない場合</summary><p class="form-note">以下の内容をすべてコピーし、.json ファイルとして保存してください。</p><textarea aria-label="バックアップJSON" readonly style="width:100%;height:200px">${esc(json)}</textarea></details>`);$('#backup-download').click();setTimeout(()=>URL.revokeObjectURL(url),600000);}
function restore(){openDialog('バックアップから復元',`<p>ファイルを検証し、件数を確認してから復元できます。現在のデータは復元前に書き出すことをおすすめします。</p>${btn('現在のデータを出力','export','','secondary')}<label class="field"><span>バックアップファイル（JSON）</span><input type="file" id="restore-file" accept="application/json,.json"></label><div id="restore-preview"></div>`);}
let restoreCandidate=null;
document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,keyId=b.dataset.id,key=b.dataset.collection;try{switch(a){
 case 'sync-login':sync.login().catch(e=>toast(e.message));break;
 case 'sync-logout':sync.logout().catch(e=>toast(e.message));break;
 case 'sync-retry':sync.retry();break;
 case 'sync-setup':openDialog('Firebase同期の設定',`<p>Webアプリの設定JSONを入力します。サービスアカウントの秘密鍵は入力しないでください。</p><form data-form="sync-config">${field('config','Firebase設定JSON','textarea','')}<button class="primary">設定を保存</button></form>`);break;
 case 'sync-conflict':syncConflict();break;
 case 'sync-cloud':sync.resolve('cloud').then(closeDialog);break;
 case 'sync-local':sync.resolve('local').then(closeDialog);break;
 case 'tab':tab=b.dataset.tab;section='';render();break;
 case 'section':tab='manage';section=b.dataset.section;render();break;
 case 'back-manage':section='';render();break;
 case 'close':closeDialog();break;
 case 'quick':openDialog('すばやく追加',`<div class="quick-grid">${[['expense','支出'],['income','収入'],['transfer','振替']].map(([k,l])=>btn(l,'new-tx',`data-kind="${k}"`,'secondary')).join('')}${btn('予定','new-tx','data-planned="true"','secondary')}</div>`);break;
 case 'new-tx':transactionForm(b.dataset.kind||'expense',b.dataset.planned==='true');break;
 case 'entity-new':entityForm(key);break;
 case 'entity-edit':entityForm(key,keyId);break;
 case 'entity-detail':entityDetail(key,keyId);break;
 case 'debt-settle':if(state.debts.find(d=>d.id===keyId)?.kind==='revolving')debtActivityForm(keyId,'repayment',true);else debtSettlementForm(keyId);break;
 case 'debt-draw':debtActivityForm(keyId,'draw');break;
 case 'debt-repay':debtActivityForm(keyId,'repayment');break;
 case 'archive':if(commit(()=>{const x=state[key].find(x=>x.id===keyId);x.active=x.active===false;})){closeDialog();if(key==='categories')toast(state.categories.find(x=>x.id===keyId).active?'カテゴリを元に戻しました。':'カテゴリを削除しました。過去の記録は残っています。');}break;
 case 'category-up':if(commit(()=>{const i=state.categories.findIndex(x=>x.id===keyId);if(i>0)[state.categories[i-1],state.categories[i]]=[state.categories[i],state.categories[i-1]];}))closeDialog();break;
 case 'finish-setup':commit(()=>state.setupDone=true);break;
 case 'tx-detail':txDetail(keyId);break;
 case 'duplicate-tx':transactionForm('expense',false,{...state.transactions.find(x=>x.id===keyId),date:today()});break;
 case 'edit-tx':transactionForm('expense',true,state.transactions.find(x=>x.id===keyId),keyId);break;
 case 'cancel-tx':if(commit(()=>cancelTransaction(state,keyId)))closeDialog();break;
 case 'event':eventDetail(keyId);break;
 case 'reverse-event':if(commit(()=>cancelGeneratedEvent(state,result.allEvents.find(e=>e.id===keyId))))closeDialog();break;
 case 'skip-event':if(commit(()=>{const e=result.allEvents.find(e=>e.id===keyId);if(e?.reserveRelease)throw Error('カードの請求は、元のカード利用の取消・返金で修正してください。');if(e?.status==='actual')throw Error('確定済みの入出金は取消・返金取引で修正してください。');const old=state.overrides.find(x=>x.sourceId===keyId);if(old)old.skipped=true;else state.overrides.push({id:id(),sourceId:keyId,skipped:true});}))closeDialog();break;
 case 'filter':filter=b.dataset.filter;render();break;
 case 'view':view=b.dataset.view;render();break;
 case 'month':calendarMonth=monthDate(calendarMonth,Number(b.dataset.delta),1);render();break;
 case 'day':selectedDate=b.dataset.date;render();break;
 case 'breakdown':breakdown();break;
 case 'savings':openDialog('貯金へ移せる金額',`<p>各口座から単独で移す場合の上限です。合算はできません。</p>${Object.entries(result.savings).map(([k,v])=>row(names('accounts',k),'将来の引落と全体の余裕を反映',yen(v))).join('')}${btn('振替を記録','new-tx','data-kind="transfer"','primary')}`);break;
 case 'reconcile':openDialog('口座残高を照合',`<p>${esc(names('accounts',keyId))}のアプリ上の残高：<strong>${yen(result.current[keyId])}</strong></p><form data-form="reconcile" data-id="${esc(keyId)}">${field('balance','実際の残高','number',result.current[keyId])}<div class="form-actions"><button class="primary">差額を調整</button>${btn('取引を確認','review-transactions','','secondary')}</div></form>`);break;
 case 'review-transactions':closeDialog();tab='record';render();break;
 case 'batch-shifts':batchShifts();break;
 case 'export':exportData();break;
 case 'restore':restore();break;
 case 'restore-confirm':if(restoreCandidate){const previous=localStorage.getItem(KEY);try{if(previous)localStorage.setItem(BACKUP,previous);localStorage.setItem(KEY,JSON.stringify(restoreCandidate));state=restoreCandidate;restoreCandidate=null;loadError='';closeDialog();render();sync.schedule();toast('バックアップを復元しました。');}catch(e){toast('保存容量不足などで復元できませんでした。');}}break;
 }}catch(e){toast(e.message);}});
document.addEventListener('change',async event=>{const el=event.target;if(el.name==='kind'&&el.closest('[data-form="entity"][data-collection="debts"]')){const form=el.closest('form');debtForm(form.dataset.id,read(form));return;}if(el.id==='schedule-group'){group=el.value;render();}if(el.name==='month'&&el.closest('[data-form="batch"]'))$('#batch-days').innerHTML=batchDays(el.value+'-01');if(el.id==='restore-file'){try{const f=el.files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('ファイルが大きすぎます（上限10MB）。');restoreCandidate=validateState(JSON.parse(await f.text()));calculate(restoreCandidate);$('#restore-preview').innerHTML=`<div class="alert info">口座 ${restoreCandidate.accounts.length}件・取引 ${restoreCandidate.transactions.length}件を復元します。現在のデータは置き換わります。</div>${btn('この内容で置き換える','restore-confirm','','primary')}`;}catch(e){restoreCandidate=null;$('#restore-preview').textContent='復元できません：'+e.message;}}});
function read(form){const out={};for(const el of form.elements){if(!el.name)continue;out[el.name]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;}return out;}
function numericCheck(x){for(const[k,v]of Object.entries(x)){if(typeof v!=='number')continue;if(!Number.isFinite(v)||Math.abs(v)>1e12)throw Error('数値が大きすぎるか不正です。');if(!['amount','balance'].includes(k)&&v<0)throw Error('0以上の数値を入力してください。');if(['closeDay','payDay','salaryDay'].includes(k)&&(!Number.isInteger(v)||v<1||v>31))throw Error('日付は1〜31です。');if(['confidence','advancePercent','deductionRate','worked','confirmed','tentative','extra'].includes(k)&&v>100)throw Error('割合は0〜100%です。');if(['amount','balance','openingOutstanding','payment','principal','budget','minimum','buffer','dailySpecial','fee'].includes(k)&&!Number.isSafeInteger(v))throw Error('金額は1円単位で入力してください。');}}
document.addEventListener('submit',event=>{const form=event.target;if(!form.dataset.form)return;event.preventDefault();const x=read(form),kind=form.dataset.form,key=form.dataset.collection,keyId=form.dataset.id;try{if(kind==='sync-config'){sync.configure(JSON.parse(x.config));return;}numericCheck(x);const success=commit(()=>{
 if(kind==='entity'){
  if(x.amount<0||x.balance<0&&key==='debts')throw Error('金額は0以上です。');if(x.payment!==undefined&&typeof x.payment==='string'){Object.assign(x,resolvePayment(state,x.payment));delete x.payment;}
  if(key==='recurring'&&x.kind==='income'&&(x.cardId||x.debitCardId))throw Error('定期収入は資産口座を選択してください。');
  if(key==='debts'){const previous=state.debts.find(d=>d.id===keyId);if(previous&&previous.kind!==x.kind&&(previous.lastOperationId||previous.settlementId))throw Error('返済履歴がある借入の種類は変更できません。新しく登録してください。');if(!keyId&&x.kind==='installment'&&x.totalPayable>0&&x.balance===0){x.balance=x.totalPayable;x.principal=Math.max(0,x.totalPayable-x.feeTotal);if(x.payment<=0&&x.months>0)x.payment=Math.ceil(x.totalPayable/x.months);}if(x.balance>0&&x.payment<=0)throw Error('返済額を入力してください。');if(x.kind==='revolving'){x.payDay=Number(x.startDate.slice(8));x.months=0;x.principal=x.balance;if(x.interestDate>today())throw Error('利息基準日は今日以前を指定してください。');}else if(x.totalPayable&&x.feeTotal>x.totalPayable)throw Error('手数料は総支払額以下です。');}
  if(key==='shifts'||key==='templates'){if(x.status==='worked'&&x.date>today())throw Error('未来の勤務を勤務済みにはできません。');const mins=t=>Number(t.slice(0,2))*60+Number(t.slice(3));let duration=mins(x.end)-mins(x.start);if(duration<=0)duration+=1440;if(x.breakMinutes>=duration)throw Error('休憩は勤務時間より短くしてください。');}
  if(key==='advances'){if(x.fee>x.amount)throw Error('手数料が先払い額を超えています。');const payrollGroup=payroll(state).find(g=>g.employerId===x.employerId&&g.date===x.payDate);const previous=state.advances.find(a=>a.id===keyId);if(!payrollGroup)throw Error('対象給料日のシフトを先に登録してください。');if(x.amount>payrollGroup.advanceAvailable+Number(previous?.amount||0))throw Error(`先払い可能額は${yen(payrollGroup.advanceAvailable+Number(previous?.amount||0))}です。勤務先の先払い設定を確認してください。`);}
  const old=state[key].find(o=>o.id===keyId);if(old)Object.assign(old,x);else state[key].push({id:id(),active:true,...x});
 }else if(kind==='transaction'){
  if(x.amount<=0)throw Error('金額は1円以上です。');Object.assign(x,resolvePayment(state,x.payment));delete x.payment;
  if(['income','transfer'].includes(x.kind)&&(x.cardId||x.debitCardId))throw Error('収入・振替には資産口座を選択してください。');if(x.kind==='transfer'&&(!x.toAccountId||x.accountId===x.toAccountId))throw Error('振替先には別の口座を選択してください。');if(x.status==='actual'&&x.date>today())throw Error('未来の日付は予定として登録してください。');if(x.kind!=='transfer'){x.toAccountId='';x.fee=0;}
  const repeat=x.repeat;delete x.repeat;const old=state.transactions.find(t=>t.id===keyId);if(old)Object.assign(old,x);else state.transactions.push({id:id(),...x});if(repeat){if(x.kind==='transfer')throw Error('振替の定期化は未対応です。');state.recurring.push({...x,id:id(),active:true,cycle:'monthly',startDate:monthDate(x.date,1,Number(x.date.slice(8))),payDay:Number(x.date.slice(8)),group:'fixed'});}
 }else if(kind==='debt-activity'){recordDebtActivity(state,keyId,x);
 }else if(kind==='debt-settlement'){settleDebt(state,keyId,x);
 }else if(kind==='settings'){state.settings={...state.settings,...x,confidence:{worked:x.worked,confirmed:x.confirmed,tentative:x.tentative,extra:x.extra}};}
 else if(kind==='event'){if(x.status==='actual'&&x.date>today())throw Error('未来の日付は予定にしてください。');const source=result.allEvents.find(e=>e.id===keyId);if(source.status==='actual')throw Error('確定済みの入出金は取消・返金で修正してください。');if(source.source==='debt'&&x.amount>0)throw Error('返済額は支出のためマイナスで入力してください。');const snapshot=x.status==='actual'?{...source,...x}:undefined;const old=state.overrides.find(o=>o.sourceId===keyId);if(old)Object.assign(old,x,{skipped:false,snapshot});else state.overrides.push({id:id(),sourceId:keyId,snapshot,...x});}
 else if(kind==='reconcile'){const amount=x.balance-result.current[keyId];if(amount)state.transactions.push({id:id(),kind:'adjustment',amount,date:today(),accountId:keyId,status:'actual',name:'残高調整'});}
 else if(kind==='batch'){const template=state.templates.find(t=>t.id===x.templateId),dates=new FormData(form).getAll('dates');if(!dates.length)throw Error('日付を選択してください。');for(const date of dates){if(x.status==='worked'&&date>today())throw Error('未来の勤務を勤務済みにはできません。');if(!state.shifts.some(s=>s.employerId===template.employerId&&s.date===date&&s.start===template.start))state.shifts.push({...template,id:id(),name:'',date,status:x.status,holiday:false});}}
 });if(success){if($('#dialog').open)closeDialog();toast('保存しました。計算結果を更新しました。');}}catch(e){toast(e.message);}});
window.addEventListener('storage',e=>{if(e.key===KEY){try{state=validateState(JSON.parse(e.newValue));render();sync.schedule();toast('別のタブで変更された内容を反映しました。');}catch{toast('別タブのデータを読み込めませんでした。');}}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});

function syncCard(){const status=sync.getStatus();return `<section class="card backup"><div><h2>PC・携帯の同期</h2><p role="status">${esc(status.message)}</p>${status.signedIn?`<small>${esc(status.email)} · 両端末で同じアカウントを使ってください。</small>`:'<small>Googleログインで家計データをFirebaseに保存・同期します。</small>'}</div><div class="actions">${status.configured?(status.signedIn?btn('再同期','sync-retry','','secondary')+btn('ログアウト','sync-logout','','secondary'):btn('Googleでログイン','sync-login','','primary')):btn('同期を設定','sync-setup','','primary')}${status.conflict?btn('変更を確認','sync-conflict','','primary'):''}</div></section>`;}
function syncConflict(){const cloud=sync.conflict();if(!cloud)return;openDialog('両端末の変更を確認',`<p>自動で上書きすると記録が失われる可能性があります。先にバックアップを保存してください。</p><dl class="detail-list"><div><dt>この端末</dt><dd>口座 ${state.accounts.length}件・取引 ${state.transactions.length}件</dd></div><div><dt>クラウド</dt><dd>口座 ${cloud.state.accounts.length}件・取引 ${cloud.state.transactions.length}件</dd></div></dl><div class="actions">${btn('この端末をバックアップ','export','','secondary')}${btn('クラウドの内容を使う','sync-cloud','','primary')}${btn('この端末でクラウドを置き換える','sync-local','','secondary')}</div><p class="form-note">選んだ内容が両端末へ反映されます。選ぶまで変更は端末内に保存されます。</p>`);}
const sync=createSync({key:KEY,disabled:testing,getState:()=>state,applyState:next=>{if(loadError)throw Error(loadError);localStorage.setItem(BACKUP,JSON.stringify(state));localStorage.setItem(KEY,JSON.stringify(next));state=next;render();},onStatus:()=>render()});
render();
if(!testing)sync.start();
